name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::notebook=6.5.2
  - conda-forge::seaborn=0.12.2
  - conda-forge::pandas=1.5.3
  - conda-forge::pip=23.0
  - conda-forge::pandas-profiling=3.6.3
  - pip:
      - wandb==0.13.10