name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::mlflow=2.1.1
  - conda-forge::pyyaml=6.0
  - conda-forge::hydra-core=1.3.1
  - conda-forge::pip=23.0
  - pip:
      - wandb==0.13.10