name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::mlflow=2.1.1
  - conda-forge::notebook=6.5.2
  - conda-forge::cookiecutter=2.1.1
  - conda-forge::hydra-core=1.3.1
  - conda-forge::matplotlib=3.6.3
  - conda-forge::pandas=1.5.3
  - conda-forge::pip=23.0
  - pip:
      - wandb==0.13.10