name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::pandas=1.1.4
  - conda-forge::pip=23.0
  - conda-forge::mlflow=2.1.1
  - conda-forge::scikit-learn=0.24.1
  - conda-forge::matplotlib=3.2.2
  - conda-forge::pillow=8.1.2
  - pip:
      - wandb==0.13.10
